name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout stm32_test repo
      uses: actions/checkout@v2
    - uses: xanderhendriks/action-build-stm32cubeide@v11.0
      with:
        project-path: stm32_test
        project-target: stm32g4
